#!/bin/bash
VERSION=$(imdb-tags -v | grep -oE [0-9]+\.[0-9]+\.[0-9]+)
URL="https://github.com/dillonhafer/imdb-tags/archive/v$VERSION.tar.gz"
SHA=$(curl -L -s $URL | shasum | sed s/[[:space:]].*//)

SED_URL="https:\/\/github\.com\/dillonhafer\/imdb-tags\/archive\/v$VERSION\.tar\.gz"
sed -i.bak "s/url.*/url \"$SED_URL\"/" Formula/imdb-tags.rb
sed -i.bak "s/sha1.*/sha1 \"$SHA\"/" Formula/imdb-tags.rb
rm Formula/imdb-tags.rb.bak
